menu:
  #Archives: /archives
  #项目作品: /projects
  关于我: /about
#rss: /atom.xml
description: 
social:
  weibo: http://weibo.com/deeper29
  github: https://github.com/Deeper29

page_comment: false
logo: /images/logo2.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-disabled

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: deeper29

#google_analytics: UA-42596364-1
favicon: images/favicon.ico